name: Java-code Formatter

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.gradle'
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: axel-op/googlejavaformat-action@v3.6.0
        with:
          args: '--replace --aosp --skip-reflowing-long-strings'
          commitMessage: "Google Java format [skip ci]"
